"""
Agent GRPO Trainer — GRPO with multi-turn tool-use rollouts.

Standard GRPO (train_grpo.py):
  generate full completion → score text → gradient update
  reward = learned reward model (chemistry yield)

Agent GRPO (this file):
  generate until <tool_call> → execute tool → inject <tool_result>
  → continue generation → score <final_answer> vs ground truth
  reward = VERIFIABLE (ground truth match, no learned RM)

This directly implements the "Agent RL Training" paradigm used in
DeepSeek-R1, OpenAI o1, and Scale's enterprise agent stack.

Key design choices:
  - Log-probs computed per-segment, each conditioned on the full context
    up to that point (including injected tool results). This is correct:
    p(turn_2 | prompt, turn_1, tool_result_1) not p(turn_2 | prompt, turn_1).
  - Tool result tokens are injected observations — they are NOT part of
    the policy gradient computation (masked out).
  - Reference policy via disable_adapter() — zero extra VRAM vs base GRPO.
"""
import logging
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import torch

from .grpo_trainer import GRPOConfig
from ..tools.python_executor import execute
from ..tools.tool_parser import parse_output
from ..reward.verifiable_reward import compute_reward, format_reward

logger = logging.getLogger(__name__)

MAX_TOOL_TURNS   = 3     # max tool calls per trajectory before forced stop
MAX_CONTEXT_LEN  = 256   # token budget per rollout (keep low to avoid OOM on log-prob pass)


SYSTEM_PROMPT = (
    "You are a reasoning agent with access to a Python executor.\n"
    "Workflow:\n"
    "  1. Think inside <think>...</think>\n"
    "  2. Call tools: <tool_call>{\"name\": \"python_executor\", "
    "\"args\": {\"code\": \"...\"}}</tool_call>\n"
    "  3. After <tool_result>, continue reasoning or give your answer\n"
    "  4. Final answer: <final_answer>...</final_answer>\n\n"
    "python_executor runs arbitrary Python and returns stdout."
)


def build_agent_prompt(problem: str) -> str:
    return f"{SYSTEM_PROMPT}\n\nProblem: {problem}\n\nSolve step by step:"


# ---------------------------------------------------------------------------
# Rollout engine
# ---------------------------------------------------------------------------

def _decode_segment(policy, response_ids: torch.Tensor) -> str:
    """Decode response_ids (1D) to text, stripping special tokens."""
    return policy.tokenizer.decode(response_ids, skip_special_tokens=True)


def run_agent_rollout(
    policy,
    prompt: str,
    max_new_tokens: int = 256,
    temperature: float = 0.9,
    max_turns: int = MAX_TOOL_TURNS,
) -> Tuple[List[str], List[str], str]:
    """
    Run a full multi-turn agent rollout.

    Returns
    -------
    model_segments : list[str]
        Text generated by the model in each turn (tool results excluded).
    tool_result_blocks : list[str]
        Injected <tool_result>...</tool_result> blocks (one fewer than or
        equal to model_segments).
    final_output : str
        Concatenation of all model_segments (the model's complete output,
        tool results excluded — used for reward scoring).
    """
    context          = prompt
    model_segments:   List[str] = []
    tool_result_blks: List[str] = []

    for _ in range(max_turns + 1):
        q_ids, r_ids = policy.generate(
            [context],
            max_new_tokens=max_new_tokens,
            temperature=temperature,
        )
        segment = _decode_segment(policy, r_ids[0])
        model_segments.append(segment)

        parsed = parse_output(segment)

        # Done — model produced a final answer
        if parsed.final_answer is not None:
            context += segment
            break

        # Tool call — execute and inject result, then continue
        if (
            parsed.tool_call is not None
            and parsed.tool_call.name == "python_executor"
        ):
            code   = parsed.tool_call.args.get("code", "print('')")
            result = execute(code)
            block  = f"\n<tool_result>\n{result.output}\n</tool_result>\n"
            tool_result_blks.append(block)
            context += segment + block
        else:
            # No tool call, no final answer — model is done
            context += segment
            break

    final_output = "".join(model_segments)
    return model_segments, tool_result_blks, final_output


# ---------------------------------------------------------------------------
# Log-prob computation over multi-turn trajectories
# ---------------------------------------------------------------------------

def _segment_logprobs(
    policy,
    context: str,
    segment: str,
) -> torch.Tensor:
    """
    Mean per-token log-prob of `segment` conditioned on `context`.
    Shape: scalar tensor.
    """
    enc_q = policy.tokenizer(
        context,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_CONTEXT_LEN,
        padding=False,
    ).to(next(policy.model.parameters()).device)

    enc_r = policy.tokenizer(
        segment,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_CONTEXT_LEN,
        padding=False,
    ).to(next(policy.model.parameters()).device)

    lp = policy.get_logprobs(enc_q["input_ids"], enc_r["input_ids"])
    return lp.mean()   # scalar


def trajectory_logprobs(
    policy,
    prompt: str,
    model_segments: List[str],
    tool_result_blks: List[str],
) -> torch.Tensor:
    """
    Sum of mean per-token log-probs across all model-generated segments,
    each correctly conditioned on the full context up to that turn
    (including injected tool results from prior turns).

    Returns a scalar tensor with gradients attached.
    """
    total_lp = torch.tensor(0.0, device=next(policy.model.parameters()).device)
    context  = prompt

    for i, segment in enumerate(model_segments):
        total_lp = total_lp + _segment_logprobs(policy, context, segment)
        context += segment
        if i < len(tool_result_blks):
            context += tool_result_blks[i]

    return total_lp / max(len(model_segments), 1)


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------

class AgentGRPOTrainer:
    """
    GRPO where each rollout is a multi-turn agent trajectory with tool use.

    Input format per example:
        {"problem": str, "answer": str, "available_tools": list[str]}

    Reward: verifiable (final_answer == answer), not learned.
    """

    def __init__(
        self,
        policy,
        config: GRPOConfig,
        device: str = "cuda",
        rank:   int = 0,
    ):
        self.policy = policy
        self.config = config
        self.device = device
        self.rank   = rank

        trainable = [p for p in policy.model.parameters() if p.requires_grad]
        self.optimizer = torch.optim.AdamW(trainable, lr=config.learning_rate)
        self.scaler    = torch.amp.GradScaler("cuda")

        try:
            import wandb
            self._wandb = wandb if wandb.run is not None else None
        except ImportError:
            self._wandb = None

        logger.info(
            f"AgentGRPOTrainer | G={config.group_size} | β={config.beta} "
            f"| clip={config.clip_ratio} | tool_turns={MAX_TOOL_TURNS}"
        )

    def train_step(self, problems: List[Dict]) -> Dict[str, float]:
        """
        For each problem, generate G agent trajectories (with tool use),
        compute verifiable rewards, apply group-relative GRPO update.
        """
        G   = self.config.group_size
        cfg = self.config

        # ---- 1. Rollout G trajectories per problem (no grad) ----
        self.policy.eval()
        all_segments:  List[List[List[str]]] = []   # [n_probs][G][n_turns]
        all_tool_blks: List[List[List[str]]] = []
        all_outputs:   List[List[str]]       = []   # [n_probs][G] final text

        with torch.no_grad():
            for item in problems:
                prompt = build_agent_prompt(item["problem"])
                group_segs, group_blks, group_outs = [], [], []
                for _ in range(G):
                    segs, blks, out = run_agent_rollout(
                        self.policy, prompt,
                        max_new_tokens=cfg.max_new_tokens,
                        temperature=cfg.temperature,
                    )
                    group_segs.append(segs)
                    group_blks.append(blks)
                    group_outs.append(out)
                all_segments.append(group_segs)
                all_tool_blks.append(group_blks)
                all_outputs.append(group_outs)

        # ---- 2. Verifiable rewards + group-relative advantages ----
        all_rewards:    List[torch.Tensor] = []
        all_advantages: List[torch.Tensor] = []

        for i, item in enumerate(problems):
            gt = item["answer"]
            rewards = torch.tensor(
                [compute_reward(o, gt) + format_reward(o) for o in all_outputs[i]],
                dtype=torch.float32,
                device=self.device,
            )
            adv = (rewards - rewards.mean()) / (rewards.std() + 1e-8)
            all_rewards.append(rewards)
            all_advantages.append(adv)

        # ---- 3. Reference log-probs (base model, no LoRA) ----
        all_ref_lp: List[torch.Tensor] = []
        with torch.no_grad(), self.policy.model.disable_adapter():
            for i, item in enumerate(problems):
                prompt = build_agent_prompt(item["problem"])
                group_ref = []
                for g in range(G):
                    ref_lp = trajectory_logprobs(
                        self.policy, prompt,
                        all_segments[i][g],
                        all_tool_blks[i][g],
                    )
                    group_ref.append(ref_lp.detach())
                all_ref_lp.append(group_ref)

        # ---- 4. Old log-probs (current policy, no grad) ----
        all_old_lp: List[torch.Tensor] = []
        with torch.no_grad():
            for i, item in enumerate(problems):
                prompt = build_agent_prompt(item["problem"])
                group_old = []
                for g in range(G):
                    old_lp = trajectory_logprobs(
                        self.policy, prompt,
                        all_segments[i][g],
                        all_tool_blks[i][g],
                    )
                    group_old.append(old_lp.detach())
                all_old_lp.append(group_old)

        # ---- 5. Policy gradient update ----
        self.policy.train()
        self.optimizer.zero_grad()
        total_loss   = 0.0
        total_reward = 0.0
        total_kl     = 0.0

        for i, item in enumerate(problems):
            prompt = build_agent_prompt(item["problem"])
            adv    = all_advantages[i]

            for g in range(G):
                old_lp = all_old_lp[i][g]
                ref_lp = all_ref_lp[i][g]
                a      = adv[g]

                with torch.amp.autocast("cuda"):
                    new_lp = trajectory_logprobs(
                        self.policy, prompt,
                        all_segments[i][g],
                        all_tool_blks[i][g],
                    )

                    log_ratio = new_lp - old_lp
                    ratio     = torch.exp(log_ratio)

                    surr1 = ratio * a
                    surr2 = torch.clamp(ratio, 1 - cfg.clip_ratio, 1 + cfg.clip_ratio) * a
                    policy_loss = -torch.min(surr1, surr2)

                    kl   = (ref_lp - new_lp).clamp(min=0)
                    loss = (policy_loss + cfg.beta * kl) / (G * cfg.gradient_accumulation_steps)

                self.scaler.scale(loss).backward()

                total_loss   += loss.item() * G * cfg.gradient_accumulation_steps
                total_kl     += kl.item()

            total_reward += all_rewards[i].mean().item()

        self.scaler.unscale_(self.optimizer)
        torch.nn.utils.clip_grad_norm_(
            [p for p in self.policy.parameters() if p.requires_grad],
            cfg.max_grad_norm,
        )
        self.scaler.step(self.optimizer)
        self.scaler.update()

        n = len(problems)
        return {
            "loss":        total_loss   / n,
            "reward_mean": total_reward / n,
            "kl":          total_kl     / n,
        }

    def train(self, problems: List[Dict]) -> Dict:
        output_path = Path(self.config.output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        history     = []
        best_reward = -1.0

        logger.info(
            f"AgentGRPO training | {self.config.num_iterations} iters "
            f"| G={self.config.group_size} | verifiable reward (GSM8K/HumanEval)"
        )

        for i in range(self.config.num_iterations):
            batch = random.sample(
                problems, min(self.config.batch_size, len(problems))
            )
            stats = self.train_step(batch)
            stats["iteration"] = i + 1
            history.append(stats)

            if self._wandb and self.rank == 0:
                self._wandb.log(
                    {
                        "agent_grpo/reward": stats["reward_mean"],
                        "agent_grpo/loss":   stats["loss"],
                        "agent_grpo/kl":     stats["kl"],
                    },
                    step=i + 1,
                )

            if self.rank == 0 and (i + 1) % self.config.log_interval == 0:
                logger.info(
                    f"[{i+1}/{self.config.num_iterations}] "
                    f"reward={stats['reward_mean']:.4f} | "
                    f"loss={stats['loss']:.4f} | kl={stats['kl']:.5f}"
                )

            if stats["reward_mean"] > best_reward:
                best_reward = stats["reward_mean"]
                if self.rank == 0:
                    self.policy.save_pretrained(str(output_path / "best"))

            if self.rank == 0 and (i + 1) % self.config.save_interval == 0:
                self.policy.save_pretrained(str(output_path / f"ckpt_{i+1:05d}"))

        logger.info(
            f"AgentGRPO complete | best_reward={best_reward:.4f} "
            f"| iters={self.config.num_iterations} | G={self.config.group_size}"
        )
        return {
            "best_reward":    best_reward,
            "num_iterations": self.config.num_iterations,
            "group_size":     self.config.group_size,
            "history":        history,
        }
